name          'waveclaw-couchpotato'
version       '0.1.0'
source        'https://github.com/RuudBurger/CouchPotatoServer'
author        'waveclaw'
license       'Apache 2.0'
summary       'CouchPotato is a search tool and download manager for Movies.'
description   ''
project_page  'https://github.com/waveclaw/puppet-couchpotato'

dependency 'puppetlabs/stdlib'
dependency 'puppetlabs/apt'
dependency 'darin/zypprepo', '>= 1.0.2'
